### ISSUE TITLE
Allow file patterns to be excluded.

### ISSUE THREAD

**Issue by sreid99** [Comcast/css_lint_ruby#2]
Would it be possible to specify files to be excluded on the command line ?

**Comment by JohnRiv** [comment]
That should be possible via the --exclude-list= command line argument. I'll look into why that's not working.

**Comment by sreidaf** [comment]
I was just asking if this option could be added - there was no mention of it in the readme. It probably does work.

Are there any other options - e.g. to disable some of the warnings ? Is it possible to put these in a yml file, or only on the command line ?

**Comment by JohnRiv** [comment]
I had a chance to look into this further. It appears --exclude-list= doesn't completely work in all cases csslint v0.9.10 (see stubbornella/csslint/issues/345), but it is fixed in the master branch. Once a new version of csslint is released, I'll update this ruby wrapper as well and then you should have that option.

You can specify which specific warnings to test for (effectively disabling the others) either via the command line or a .csslintrc file. More details are available over at the [CSS Lint wiki page on the Command-line Interface](https://github.com/stubbornella/csslint/wiki/Command-line-interface#--errors)

**Comment by sreidaf** [comment]
Thanks - I'll try out the new version once it's released.
